INSERT INTO movies (title, description, poster_url, audio_language, country, genre, release_year, url) VALUES
-- English movies
('The Shawshank Redemption', 'A banker convicted of murder forms an unlikely friendship in prison while holding onto hope for freedom.', 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg', 'en', 'United States', 'Drama', 1994, 'https://www.imdb.com/title/tt0111161/'),
('Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into a CEO''s mind.', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg', 'en', 'United States', 'Sci-Fi', 2010, 'https://www.imdb.com/title/tt1375666/'),
('The King''s Speech', 'The story of King George VI and his struggle to overcome a debilitating stammer with the help of an unorthodox speech therapist.', 'https://m.media-amazon.com/images/M/MV5BMzU5MjEwMTg2Nl5BMl5BanBnXkFtZTcwNzM3MTYxNA@@._V1_.jpg', 'en', 'United Kingdom', 'Drama', 2010, 'https://www.imdb.com/title/tt1504320/'),
-- Spanish movies
('El laberinto del fauno', 'En la España de 1944, una niña escapa a un mundo de fantasía mientras su padrastro, un capitán del ejército, persigue a los guerrilleros.', 'https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNkNGRhNjdkMjBlXkEyXkFqcGc@._V1_.jpg', 'es', 'Spain', 'Fantasy', 2006, 'https://www.imdb.com/title/tt0457430/'),
('Roma', 'Una trabajadora doméstica en la Ciudad de México de los años 70 navega la vida familiar y la agitación política.', 'https://m.media-amazon.com/images/M/MV5BMTU0OTc3ODk4Ml5BMl5BanBnXkFtZTgwMzM4NzI5NjM@._V1_.jpg', 'es', 'Mexico', 'Drama', 2018, 'https://www.imdb.com/title/tt6155172/'),
('El secreto de sus ojos', 'Un oficial de justicia retirado escribe una novela basada en un caso de asesinato sin resolver que lo ha perseguido durante veinticinco años.', 'https://m.media-amazon.com/images/M/MV5BY2FhZGFjYTItMDhiYi00MGUwLThlNjktNjQwNDYyYmEyZjQwXkEyXkFqcGc@._V1_.jpg', 'es', 'Argentina', 'Thriller', 2009, 'https://www.imdb.com/title/tt1305806/');
